shop:
  outputs:
    dev:
      dataset: shop_queries
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: C:\Users\TheDa\Desktop\Ultima pasta\de-analytics-ebgineering-main\weighty-legend-382122-29acdc3f7a01.json
      location: US
      method: service-account
      priority: interactive
      project: weighty-legend-382122
      threads: 1
      type: bigquery
  target: dev
